### ISSUE TITLE
ipexrun --multi-task-manager error

### ISSUE THREAD

**Issue by hdtv35** [Nuullll/ipex-sd-docker-for-arc-gpu#15]
Hello! Thank you so much for making this container! I've been using it for over a month now with great success. I just upgraded to v0.6 but am getting this ipexrun error: `ipexrun: error: unrecognized arguments: --multi-task-manager`
I am on Ubuntu 22.04 on kernel 6.3.5-060305-generic using an Arc A770 16GB. I also did some updates at the same time I upgraded the container which may have caused the issue. Thank you!
```
hdtv35@artanis:~/docker-mount/sd-webui$ sudo docker run -it --device /dev/dri -v ~/docker-mount/sd-webui:/sd-webui -v deps:/deps -v huggingface:/root/.cache/huggingface -p 7860:7860 -
-name sd-webui nuullll/ipex-arc-sd:latest --upgrade
Create and activate python venv
Launching ipexrun launch.py...
/deps/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
usage: ipexrun [-h] [--multi_instance] [--distributed] [-m] [--no_python] [--enable_tcmalloc] [--enable_jemalloc] [--use_default_allocator] [--disable_iomp] [--nnodes]
               [--nproc_per_node] [--ccl_worker_count] [--master_addr] [--master_port] [--hostfile] [--more_mpi_params] [--ncore_per_instance] [--skip_cross_node_cores]
               [--ninstances] [--instance_idx] [--latency_mode] [--throughput_mode] [--node_id] [--use_logical_core] [--disable_numactl] [--disable_taskset] [--core_list]
               [--benchmark] [--log_path] [--log_file_prefix] [--auto_ipex] [--dtype] [--auto_ipex_verbose] [--disable_ipex_graph_mode]
               program ...
ipexrun: error: unrecognized arguments: --multi-task-manager
```

**Comment by Nuullll** [comment]
@hdtv35 Could you also try to append `--reinstall` after `--upgrade`. Might caused by outdated `ipexrun` version.

**Comment by Disty0** [comment]
Remove the deps volume then it will install PyTorch 2.0.
`docker volume rm deps`

**Comment by hdtv35** [comment]
> Remove the deps volume then it will install PyTorch 2.0. `docker volume rm deps`

Thank you both, this worked! Any way I can buy you both a coffee?

**Comment by Nuullll** [comment]
Thank you! A star for this repo is enough for me :-P
