### ISSUE TITLE
Abort when loading model

### ISSUE THREAD

**Issue by Alkaid-C** [Nuullll/ipex-sd-docker-for-arc-gpu#21]
Every time I try to load a model, the following error message will pop out and the container will stop.

It seems that the error occurs when the program intends to assign tasks to CPU cores. My CPU is CPU 12900k. Is the p-core e-core design causing the problem?

`Abort was called at 62 line in file:
./shared/source/os_interface/os_interface.h
Aborted
╭─────Traceback (most recent call last) ─────╮
│ /deps/venv/bin/ipexrun:8 in <module>

│

│   5 from intel_extension_for_pytorch.launcher import main

│   6 if __name__ == '__main__': 

│   7    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0]) 

│ ❱ 8    sys.exit(main()) 

│   9  

│ 

│ /deps/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/launcher.py:109 in main 

│

│   106 │   │   sys.argv.insert(1, "CPU")

│   107 │   args = parser.parse_args() 

│   108 │   if args.backend == "CPU": 

│ ❱ 109 │   │   cpu_run_main_with_args(args)

│   110 │   elif args.backend == "xpu":

│   111 │   │   xpu_run_main_with_args(args)

│   112 │   else: 

│  

│ /deps/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch/launch.py:453 in 

│ run_main_with_args

│ 

│   450 │   else: 

│   451 │   │   launcher = launcher_multi_instances

│   452 │    

│ ❱ 453 │   launcher.launch(args)

│   454 │   for x in sorted(set(os.environ.keys()) - env_before):

│   455 │   │   logger.debug(f"{x}={os.environ[x]}")

│   456

│  

│ /deps/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch/launcher_multi_in

│ stances.py:316 in launch 

│   

│   313 │   │   │   │   p = process["process"]    

│   314 │   │   │   │   p.wait()  

│   315 │   │   │   │   if p.returncode != 0:  

│ ❱ 316 │   │   │   │   │   raise subprocess.CalledProcessError(   

│   317 │   │   │   │   │   │   returncode=p.returncode, cmd=process["cmd"]  

│   318 │   │   │   │   │   )  

│   319 │   │   finally:  

╰────────────────────────────╯

CalledProcessError: Command 'taskset -c 0,2,4,6,8,10,12,14,16,18,20,22 /deps/venv/bin/python3 -u launch.py -f --use-ipex --listen --insecure' returned non-zero exit status 134.`

**Comment by Disty0** [comment]
Disable your iGPU from the BIOS or the Device Manager.
