### ISSUE TITLE
vram overflow after continuous generate pictures / 连续出图后显存溢出

### ISSUE THREAD

**Issue by Michael-Altmann** [Nuullll/ipex-sd-docker-for-arc-gpu#8]
# vram overflow after continuous generate pictures  
# 连续出图后显存溢出
## how to reproduce
Keep generate with any web-ui settings, vram usage will raise and finally overflow after fully used. (Causing web-ui crash at the same time.)
I tried manually install oneAPI kit in Ubuntu 22.04 , all led to a same crash.
## results expected
Vram is fully loaded but not causing crash.
## log in web-ui
`RuntimeError: DPCPP out of memory. Tried to allocate 518.00 MiB (GPU
Time taken: 0.51sTorch active/reserved: 2620/3166 MiB, Sys VRAM: 2073/13005 MiB (15.94%)`
![image](https://github.com/Nuullll/ipex-sd-docker-for-arc-gpu/assets/57740314/816dbb5f-c156-4c0c-8fdf-d46d5f0117e7)
## env
windows 11 with 32g ram
intel 13600kf+arc a770 16g

**Comment by Nuullll** [comment]
I've seen the same error message several times while I'm developing/testing the docker image.
But recently I didn't see this again. Although my GPU memory usage always goes up to ~100% after a few image generations, there's no `RuntimeError` and everything seems to work just fine.

Recalling major changes in my environment:
- Upgrade Arc Windows driver from version 4382 to 4502
- Keep SD.Next codebase up-to-date

Could you please upgrade your web ui codebase by:
```powershell
docker run -it `
--device /dev/dxg `
-v /usr/lib/wsl:/usr/lib/wsl `
-v $home\docker-mount\sd-webui:/sd-webui `
-v deps:/deps `
-p 7860:7860 `
--rm `
nuullll/ipex-arc-sd:v0.2 --upgrade
```

And then attach a screenshot of the `System Info` tab? 
![image](https://github.com/Nuullll/ipex-sd-docker-for-arc-gpu/assets/7253534/1c7d7b89-c51b-401b-b1fb-431bbeaa1e72)

**Comment by Nuullll** [comment]
BTW, you could try `Batch count = 40`, which should be equivalent to manually generating 40 images 1-by-1.

**Comment by Michael-Altmann** [comment]
> BTW, you could try `Batch count = 40`, which should be equivalent to manually generating 40 images 1-by-1, to see if the same problem could be reproduced.

## In Automatic1111's web-ui:
The process keeps going as varm usage reaches 100%, and after 3 more generates the web-ui crashed as well as Windows system UI, the whole desktop stuck. 
I'm trying upgrading SD-next to the latest version and try again with the same settings.

**Comment by Nuullll** [comment]
Okay, I encountered the same error after a few image-to-image generations.
```
Prompt:

DPCPP out of memory. Tried to allocate 186.00 MiB (GPU
Time taken: 22.18s | GPU active 3754 MB reserved 3888 MB | System peak 3754 MB total 13005 MB
```

**Comment by Nuullll** [comment]
Good news. According to the @a-One-Fan's findings in https://github.com/intel/intel-extension-for-pytorch/issues/388, I did some local experiments with [SD.Next](https://github.com/vladmandic/automatic) by commenting out all `torch.xpu.empty_cache()`.

## Results

![屏幕截图 2023-07-12 170333](https://github.com/Nuullll/ipex-sd-docker-for-arc-gpu/assets/7253534/6aca7792-ac1c-4772-88dc-2a0927188933)

The VRAM usage stats is obtained by [`xpu-smi`](https://github.com/intel/xpumanager) in native windows.

**Comment by Nuullll** [comment]
Fixed by @Disty0 : https://github.com/vladmandic/automatic/commit/c3a4293f2227fe77b9ea908c99a1bda2aef43175

Please upgrade `SD.Next` with `--upgrade` flag. If you are using the docker image, you could follow the instruction here: [English](https://blog.nuullll.com/ipex-sd-docker-for-arc-gpu/#/getting-started?id=upgrade-sdnext-source-code) / [中文](https://blog.nuullll.com/ipex-sd-docker-for-arc-gpu/#/zh-cn/getting-started?id=%e6%9b%b4%e6%96%b0sdnext%e6%ba%90%e4%bb%a3%e7%a0%81)

Feel free to reopen if the issue still exists after upgradation.

**Comment by Michael-Altmann** [comment]
Thanks for following up.
